defaults:
  - _build
  - /preprocessor/normalizer: formal_ko
  - /preprocessor/segmenter: kss
  - override /io/loader/parser: plaintext

name: econ_news_kr_code
fullname: Korean Economic News Dataset
description: Korean Economic News Dataset
license:
homepage: https://www.bigkinds.or.kr
version: 1.0.0
lang: ko
category: formal
domain: econ
column_info:
  data:
    id: int
    code: str
    filename: str

io:
  data_sources:
    train: \d{8}_\d{8}\.zip
  loader:
    multiprocessing_at: _load_archive
    decode_before_parse: true
    filetype:
    data:
      field:
      item:
        filename: filename
        lieno: lineno
        text: text
    parser:
      split: true

pipeline:
  _transform_:
    - split_column
    - reset_index
  _preprocess_:
    - normalize
    - filter_length
    - drop_duplicates

  filter_length:
    min_length: 10

  split_column:
    source: text
    target:
      - file
      - codes
    split:
      pat: ","
      expand: true
