defaults:
  - corpora

name:
  - esg_report
  - modu_news
  - sec_report
data_dir: /workspace/data/projects/eKonPLM/data/corpora/corpus-csv-norm
use_name_as_subdir: false
data_files:
filetype: .csv
column_info:
  keys:
    id: 
      - id
      # - chunk_no
    text: text
  data:
    id: int
    chunk_no: int
    text: str
autoload: false
verbose: true
collapse_ids: false