defaults:
  - corpora

name:
  - esg_report
data_dir: ${dir.project}/esg_report_topic/corpus
metadata_dir: ${dir.corpus}/esg_report
use_name_as_subdir: false
data_files:
  train: esg_report_nouns.parquet
meta_files:
  train: meta-esg_report-train.parquet
filetype: .parquet
column_info:
  keys:
    id: 
      - id
      - chunk_id
    text: text
  data:
    id: int
    chunk_id: int
    text: str
autoload: false
verbose: true
collapse_ids: false