defaults:
  - corpora

name: sec_report
data_dir: ${dir.project}/${corpus.name}_topics/corpus
metadata_dir: ${dir.corpus}/${corpus.name}
use_name_as_subdir: false
data_files:
  train: ${corpus.name}_filtered_ex_stopwords.parquet
meta_files:
  train: meta-${corpus.name}-train.parquet
filetype: .parquet
column_info:
  keys:
    id: 
      - id
      - chunk_id
    text: text
    merge_meta_on:
      - id
  timestamp: 
    key: rdate
    format: 
    params:
  data:
    id: int
    chunk_id: int
    timestamp: datetime64
    text: str
autoload: false
verbose: true
collapse_ids: false