# @package _global_
defaults:
  - /model/transformer: simple_t5_classification
  - /model/transformer/pretrained: t5-base
  - override /cmd: transformer_finetune
  - override /dataset: simple

dataset:
  name: financial_phrasebank 
  verbose: false
model: 
  transformer:
    name: ${dataset.name}
    _call_:
      - train
      - eval
    config:
      num_train_epochs: 2
      max_seq_length: 256
      train_batch_size: 8
      eval_batch_size: 8
    labels:
      - positive
      - neutral
      - negative
