# @package _global_
defaults:
  - /model/transformer: simple_classification
  # - /model/transformer/pretrained: ekonbert-base
  - /model/transformer/pretrained: ekonelectra-base
  - override /cmd: transformer_finetune
  - override /dataset: finsent_kr

dataset:
  verbose: false
model: 
  transformer:
    name: finsent_kr
    _call_:
      - eval
    config:
      num_train_epochs: 2
      max_seq_length: 256
      train_batch_size: 32
      eval_batch_size: 32
    labels:
      - positive
      - neutral
      - negative
