# @package _global_
defaults:
  - /model/topic: esg_topics2
  # - override /corpus: esg_nouns
  - override /task: dataframe_task

task:
  name: esg_topics2_20_sampling
  verbose: true
  pipeline:
    _pipeline_:
      - load_dataframe
      - filter_query
      - sampling
      # - merge_dataframe
      # - save_dataframe
    load_dataframe:
      data_dir: ${model.topic.model_dir}
      data_file: esg_topics2-LDA.k30-topic_dists_labeled.csv
    save_dataframe:
      output_dir: ${model.topic.output_dir}/corpus
      output_file: esg_topics2_sample_for_label.csv
    sampling:
      groupby:
        - corpus
        - topic_num
      sample_size_per_group: 200
      value_var: topic_weight
      output_dir: ${model.topic.output_dir}/sample
      output_file: esg_topics2-sample.csv
      columns_to_keep:
        - corpus
        - id
        - topic_num
        - topic_weight
        - top_topics
    filter_query:
      query: 
        - topic_weight > 0.4
        - topic_no < 16
