# @package _global_
defaults:
  - /model/topic: esg_topics2
  - override /corpus: esg_topics2_nouns 
  - override /task: topic_task

task:
  name: esg_topic2
  verbose: true
  topic:
    _subtasks_:
      # - load_corpus
      # - train_model
      - load_model
      # - visualize
      # - topic_wordclouds
      # - infer_topics
      - label_topics
      - save_labels
      # - export_processed

    load_model:
      model_file: esg_topics2-LDA.k30.mdl
    label_topics:
      rebuild: true
    # infer_topics:
    save_labels:
      names:
        0: E(기후변화)
        1: E(친환경차)
        2: E(환경영향)
        3: S(노조)
        4: S(일자리)
        5: S(사회적 가치)
        6: S(협력사)
        7: S(사회공헌)
        8: S(안전/사고)
        9: S(정보보호)
        10: S(소비자)
        11: G(지배구조)
        12: G(기업윤리)
        13: G(배당정책)
        14: G(조직/리더쉽)
        15: S(기술/혁신)