#.users.yaml
# Users are provided as a list
# htpasswd -nbB "" my-new-password
# :$apr1$n0C4S20a$noG.3yWxH1OIKfFITgzl30
- username: user1
  hashed_password: <generated-hashed-password> # See the previous section above
  api_key: "ThisIsTheUser1APIKEY"
  workspaces: [] # This user will only have her user workspace available
# - username: user2
#   hashed_password: <generated-hashed-password> # See the previous section above
#   api_key: "ThisIsTheUser2APIKEY"
#   workspaces: ['client_projects'] # access to her user workspace and the client_projects workspace
# - username: user3
#   hashed_password: <generated-hashed-password> # See the previous section above
#   api_key: "ThisIsTheUser2APIKEY" # this user can access all workspaces (including
