# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: eKorpkit Tutorials
author: Young Joon Lee
email: entelecheia@hotmail.com
logo: ekorpkit.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  exclude_patterns:
    - '*.ipynb'
  allow_errors: true
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ekorpkit.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/entelecheia/ekorpkit-book  # Online location of your book
  path_to_book: ekorpkit-book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-FN4GFT8HP8

launch_buttons:
  colab_url: "https://colab.research.google.com"
  # jupyterhub_url: "http://14.49.229.3:18888"

# parse:
#   myst_enable_extensions:
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default!
#     - html_image
#     - amsmath
