# @package _global_
defaults:
  - override /task: corpus_task

corpus:
  name: sec_report
task:
  name: sec_report_topics
  data_dir: ${dir.project}/${task.name}
  verbose: true
  merge_metadata: false
  pipeline:
    _pipeline_:
      tokenize: tokenize
      save_dataframe: save_dataframe
      extract_tokens: extract_tokens
      eval_columns: eval_columns
      chunk: chunk
      explode_splits: explode_splits
      save_dataframe2: save_dataframe
    tokenize:
      userdic_path: /workspace/projects/eKonPLM/resources/mecab/userdict_ekon.dic
      # preprocessor:
      #   verbose: false
    extract_tokens:
      nouns_only: true
    save_dataframe:
      task_dir: corpus
      output_file: ${corpus.name}_tokenized.parquet
    save_dataframe2:
      task_dir: corpus
      output_file: ${corpus.name}_nouns.parquet
    chunk:
      chunk_size: 350
    explode_splits:
      id_key:
        - id
      split_key: chunk_id
      separator: '\n\n'
    eval_columns:
      engine: python
      expressions:
        text: "text.str.lower()"

