# @package _global_
defaults:
  - override /task: corpus_task

corpus:
  name: sec_report
task:
  name: sec_report_topics
  data_dir: ${dir.project}/${task.name}
  verbose: true
  merge_metadata: true
  pipeline:
    _pipeline_:
      stdout_samples: stdout_samples
