# @package _global_
defaults:
  - override /task: dataframe
  - override /cmd: task

corpus:
  name: sec_report
task:
  name: sec_report_topics
  data_dir: ${dir.project}/${task.name}
  verbose: true
  pipeline:
    _pipeline_:
      load_dataframe: load_dataframe
      extract_tokens: extract_tokens
      save_dataframe: save_dataframe
    load_dataframe:
      data_dir: ${..save_dataframe.output_dir}
      data_file: ${corpus.name}_sample.parquet
    extract_tokens:
      nouns_only: false
      filter_stopwords_only: true
      stopwords_path: /workspace/data/ekorpkit-config/resources/company_names.txt
    save_dataframe:
      task_dir: corpus
      output_file: ${corpus.name}_sample_ex_stopwords.parquet
