# @package _global_
defaults:
  - override /corpus: sec_report_filtered
  - override /task: corpus
  - override /cmd: task

corpus:
  autoload: true
task:
  # corpus: ${..corpus}
  name: sec_report_topics
  data_dir: ${dir.project}/${task.name}
  verbose: true
  pipeline:
    _pipeline_:
      stdout_samples: stdout_samples
