# @package _global_
defaults:
  - override /corpus: sample_report_nouns
  - override /task: corpora_task

corpus:
  autoload: true
task:
  name: sec_report_topics
  data_dir: ${dir.project}/${task.name}
  verbose: true
  merge_metadata: false
  pipeline:
    _pipeline_:
      stdout_samples: stdout_samples
