# @package _global_
defaults:
  - /visualize/plot: lineplot
  - override /task: dataframe_task

task:
  name: sec_report_topics
  data_dir: ${dir.project}/${task.name}
  verbose: true
  pipeline:
    _pipeline_:
      load_dataframe: load_dataframe
      pivot: pivot
      eval_columns0: eval_columns
      melt: melt
      aggregate_columns: aggregate_columns
      eval_columns: eval_columns
      pivot2: pivot
      # save_dataframe: save_dataframe
      plot: plot
      
    load_dataframe:
      data_dir: ${task.data_dir}/topics
      data_file: sec_report_topic_dists_company_year.parquet
    pivot:
      index:
        - year
        - CMP_CD
      columns:
        - topic_num
      values:
        - topic_weight
    eval_columns0:
      expressions:
        E: topic0
        S: topic1
        G: topic2
        G2: topic2+topic6
        G3: topic2+topic4+topic6
        ESG: E+S+G
        ESG2: E+S+G2
        ESG3: E+S+G3
    melt:
      id_vars:
        - year
        - CMP_CD
      value_vars: 
      var_name: topic_num
      value_name: topic_weight
    aggregate_columns:
      aggregations:
        topic_weight: [std, mean]
      groupby:
        - year
        - topic_num
      reset_index: true
    eval_columns:
      expressions:
        topic_cv: topic_weight_std / topic_weight_mean
    pivot2:
      index:
        - year
      columns:
        - topic_num
      values:
        - topic_cv
    eval_columns2:
      expressions:
        E: topic0
        S: topic1
        G2: topic2
        G: topic2+topic6
        ESG: E+S+G
        ESG2: E+S+G2
    plot:
      visualize: ${visualize}

visualize:
  plot:
    output_dir: ${task.data_dir}/figs
    output_file: topic_trends_cv.png
    columns:
      xvalue: year
      yvalue: ['ESG', 'E', 'S', 'G']
    figure:
      xlabel: Year
      ylabel: Coefficient of Variation
      title: Coefficient of Variation of ESG Topic Weights
      xlim:
        left: 2004
        right: 2020
      # legend:
      #   labels: ['ESG', 'E', 'S', 'G']
      # xticks:
      #   ticks: [2005, 2010, 2015, 2020]
      #   labels: [2005, 2010, 2015, 2020]
      xtickmajorformatterfunc: 'ticker.FormatStrFormatter("%d")'
      # ytickmajorformatterfunc: 'ticker.PercentFormatter(1.0, decimals=1)'
