# @package _global_
defaults:
  - /model/topic: sec_report_topics
  - override /corpus: sec_report_nouns
  - override /task: topic_task

task:
  name: sec_report_topics
  verbose: true
  topic:
    _subtasks_:
      - load_corpus
      - train_model
      # - load_model
      - visualize
      - topic_wordclouds
      # - infer_topics
      # - label_topics
      # - save_labels
      # - export_processed
    train_model:
      k: 50
      iterations: 300
    load_model:
      model_file: sec_report_topics-LDA.k30.mdl
    topic_wordclouds:
      ncols: 5
      nrows: 5
    label_topics:
      rebuild: true
    # infer_topics:
    save_labels:
      names:
        0: E(기후변화)
        1: E(친환경차)
        2: E(환경영향)
        3: S(노조)
        4: S(일자리)
        5: S(사회적 가치)
        6: S(협력사)
        7: S(사회공헌)
        8: S(안전/사고)
        9: S(정보보호)
        10: S(소비자)
        11: G(지배구조)
        12: G(기업윤리)
        13: G(배당정책)
        14: G(조직/리더쉽)
        15: S(기술/혁신)