# @package _global_
defaults:
  - override /task: corpus_task

task:
  verbose: true
  pipeline:
    _pipeline_:
      - sampling
    sampling:
      groupby:
      sample_size_per_group: 0.001
      value_var: text
      output_dir: ${dir.data}/${project}/corpora/sample
      output_file: ${corpus.name}-sample.csv
