# @package _global_
defaults:
  - override /task: dataframe_task

task:
  data_dir: ${dir.project}/dataframe/tmp
  data_file: pmc_noncomm/pmc_noncomm-train-000.parquet
  pipeline:
    _pipeline_:
      - load_dataframe
      - normalize
      - filter_length
      - split_dataframe
      - segment
      - concat_dataframes
      - drop_duplicates
      - save_dataframe
    save_dataframe:
      output_dir: ${dir.project}/dataframe/tmp
      output_file: ${..load_dataframe.data_file}
    split_dataframe:
      num_splits: 100
    filter_length:
      min_length: 30
      max_length: 10_000
    drop_duplicates:
      apply_to:
        - text
    segment:
      segmenter:
        merge_lines: true
        merge_level: article
        verbose: 100
        max_split_length: 11_000
    normalize:
      normalizer:
        single_quotes_only: true
        regular_parentheses_only: true