# @package _global_
defaults:
  - override /mode: debug

project:
  name: esgml
dir:
  workspace: /workspace
  data: ${.workspace}/data/tbts
  project: ${.workspace}/data/tbts/${project.name}
  dataset: ${.workspace}/data/datasets
  model: ${.workspace}/data/tbts/models
  output: ${.workspace}/data/outputs
  corpus: ${.dataset}/corpus/ekorpkit
