# @package _global_
defaults:
  - override /mode: debug

project: esgml
dir:
  workspace: /workspace
  data: ${.workspace}/data/tbts
  project: ${.workspace}/data/tbts/${project}
  dataset: ${.workspace}/data/datasets
  model: ${.workspace}/data/tbts/models
  output: ${.workspace}/data/outputs
  corpus: ${.dataset}/corpus/ekorpkit
env:
  os:
    MODIN_ENGINE: joblib
    