defaults:
  - simple_auto

_target_: ekorpkit.datasets.loader.Datasets
name: finsent_kr
datasets:
  - analystsent_kr
  - finphrase_kr
data_dir: ${dir.dataset}/simple
column_info:
  keys:
    id: id
  data:
    id: int
    labels: str
    text: str

