defaults:
  - default
  
model_name: sample_report_topics
verbose: true
ngram:
  min_cf: 10
  min_df: 5
  max_len: 10
  max_cand: 5000
  min_score: -10
  normalized: true
  delimiter: ''
files:
  stoplist: ${..model_dir}/stopwords-extra.txt